### ISSUE TITLE
Hello richRong, let's start a project in github

### ISSUE THREAD

**Issue by FUQIANGCAO** [stonelsr/rent#1]
Please reply me when you see this issues

**Comment by FUQIANGCAO** [comment]
oh, why are you so busy?

**Comment by FUQIANGCAO** [comment]
Dear richRong:
    I learned breastroke,backstroke and freestyle last weekend. We can  swin together in GuangZhou in National Day. Besides, I'm not happy that you didn't reply to me.

**Comment by stonelsr** [comment]
Dear fuQiang Cao
I'm very sorry I didn't reply to your message. At the same time, I'm very happy for you to learn breaststroke. Welcome to Guangzhou when you have time
